import blogSlugs from './data/blogSlugs.cjs';
import jsonLd from './utils/jsonLd.cjs';
import seoMeta from './utils/seoMeta.cjs';

const { buildJsonLd } = jsonLd;

/* ─────────────────────────────────────────────
 * SEO constants & helpers
 *
 * seoMeta.cjs used to be duplicated inline here, which meant three copies of
 * ROUTE_META (this file, seoMeta.js, seoMeta.cjs) that had to be edited in
 * lockstep. It is imported instead now — jsonLd.cjs already pulls it into the
 * Worker bundle, so this adds no bytes and removes the drift.
 * ───────────────────────────────────────────── */

const { SITE_ORIGIN, getMetaForPath, escapeHtml, stripExistingSeoTags, buildSeoTags } = seoMeta;

// Live blog slugs (generated by scripts/gen-seo-assets.mjs). Old WordPress
// posts lived at the site root (/<slug>); we 301 those to /blog/<slug>.
const BLOG_SLUGS = new Set(blogSlugs);

/* ─────────────────────────────────────────────
 * JSON-LD structured data (schema.org)
 *
 * The graph itself lives in src/utils/jsonLd.cjs so the build-time
 * prerenderer, this Worker and the Node render server all emit byte-identical
 * markup. scripts/prerender.mjs already bakes it into every page, so this
 * injection only matters on the paths the Worker actually serves.
 * ───────────────────────────────────────────── */

function injectSeoTags(html, pathname) {
  const meta = getMetaForPath(pathname);

  // Strip first: a page can arrive here already carrying a baked block, and
  // two canonicals is worse than none.
  html = stripExistingSeoTags(html);
  html = html.replace(/<title>[^<]*<\/title>/, `<title>${escapeHtml(meta.title)}</title>`);

  return html.replace(
    '</title>',
    `</title>\n    ${buildSeoTags(pathname)}\n    ${buildJsonLd(pathname)}`,
  );
}

/* ─────────────────────────────────────────────
 * Static-asset extension set (pass-through)
 * ───────────────────────────────────────────── */

const STATIC_EXT = /\.(?:js|css|webp|svg|png|jpg|jpeg|woff2|xml|txt|json|ico|gif|map)$/i;

/* ─────────────────────────────────────────────
 * Webhook helpers
 * ───────────────────────────────────────────── */

const RESPONSE_HEADERS = {
  'Content-Type': 'application/json',
  'Cache-Control': 'no-store',
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Methods': 'POST, OPTIONS',
  'Access-Control-Allow-Headers': 'Content-Type',
};

function jsonResponse(status, body) {
  return new Response(JSON.stringify(body), {
    status,
    headers: RESPONSE_HEADERS,
  });
}

async function readTextSafely(response) {
  try {
    return await response.text();
  } catch {
    return '';
  }
}

function requestMeta(request) {
  return {
    forwarded_for: request.headers.get('cf-connecting-ip') || request.headers.get('x-forwarded-for') || null,
    user_agent: request.headers.get('user-agent') || null,
    referer: request.headers.get('referer') || request.headers.get('referrer') || null,
  };
}

async function forwardWebhook(request, webhookUrl, labels) {
  if (request.method === 'OPTIONS') {
    return new Response(null, {
      status: 204,
      headers: RESPONSE_HEADERS,
    });
  }

  if (request.method !== 'POST') {
    return jsonResponse(405, { error: 'Method not allowed.' });
  }

  if (!webhookUrl) {
    return jsonResponse(500, { error: `${labels.envName} is not configured.` });
  }

  let payload;
  try {
    payload = await request.json();
  } catch {
    return jsonResponse(400, { error: 'Invalid JSON payload.' });
  }

  const forwardedPayload = {
    ...payload,
    request: requestMeta(request),
  };

  try {
    const webhookResponse = await fetch(webhookUrl, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(forwardedPayload),
    });

    if (!webhookResponse.ok) {
      const body = await readTextSafely(webhookResponse);
      return jsonResponse(502, {
        error: labels.rejectedMessage,
        status: webhookResponse.status,
        body: body.slice(0, 500),
      });
    }

    return jsonResponse(200, { ok: true });
  } catch (error) {
    return jsonResponse(502, {
      error: labels.failedMessage,
      message: error.message,
    });
  }
}

/* ─────────────────────────────────────────────
 * /.well-known/* — agent & client discovery documents
 *
 * Without this, an unpublished discovery document falls through to the SPA
 * fallback and answers 200 with the HTML shell. An agent asking for
 * application/linkset+json or text/markdown then has to guess that a web page
 * means "absent". Serve whatever is genuinely published under .well-known and
 * answer a plain 404 for the rest.
 *
 * Routed here by run_worker_first in wrangler.toml.
 * ───────────────────────────────────────────── */

async function wellKnownResponse(request, env) {
  const assetResponse = await env.ASSETS.fetch(request);
  const contentType = assetResponse.headers.get('content-type') || '';

  // A real published document is JSON, markdown or plain text. HTML back from
  // the asset server means no such file exists and the SPA fallback answered.
  if (assetResponse.ok && !contentType.includes('text/html')) {
    return assetResponse;
  }

  return jsonResponse(404, {
    error: 'Not found.',
    detail: 'This site publishes no discovery document at this path.',
  });
}

/* ─────────────────────────────────────────────
 * Legacy WordPress URL cleanup (mirrors public/.htaccess)
 * Returns a Response for legacy paths, or null to continue normal handling.
 * ───────────────────────────────────────────── */

function gone() {
  return new Response('Gone', {
    status: 410,
    headers: { 'Content-Type': 'text/plain; charset=utf-8', 'Cache-Control': 'no-store' },
  });
}

function forbidden() {
  return new Response('Forbidden', {
    status: 403,
    headers: { 'Content-Type': 'text/plain; charset=utf-8', 'Cache-Control': 'no-store' },
  });
}

function legacyWordPressResponse(url) {
  const { pathname, search } = url;

  // preconception-care → /preconception (301)
  if (pathname.replace(/\/+$/, '') === '/preconception-care') {
    return Response.redirect(`${SITE_ORIGIN}/preconception`, 301);
  }

  // WordPress attachment / post-id query params (?attachment_id= / ?p=) → 410 Gone
  if (/[?&](?:attachment_id|p)=/.test(search)) return gone();

  // xmlrpc.php → 403 Forbidden
  if (/^\/xmlrpc\.php$/i.test(pathname)) return forbidden();

  // wp-json / wp-admin / wp-login(.php) / wp-includes / wp-content → 410 Gone.
  // The trailing [/.] also catches file forms like /wp-login.php.
  // (note: /wp-styles/* are real assets and are intentionally NOT matched)
  if (/^\/wp-(?:admin|login|includes|content|json)(?:[/.]|$)/i.test(pathname)) {
    return gone();
  }

  // RSS / comment / trackback feeds (…/feed) → 301 to homepage
  if (/\/feed\/?$/i.test(pathname)) return Response.redirect(`${SITE_ORIGIN}/`, 301);

  // Author archives → 301 to About page
  if (/^\/author\/.+/i.test(pathname)) return Response.redirect(`${SITE_ORIGIN}/about-me`, 301);

  // WordPress pagination artifacts: /<parent>/page/N → /<parent>, /page/N → /
  const pageMatch = pathname.match(/^(\/.*?)?\/page\/\d+\/?$/i);
  if (pageMatch) {
    const parent = pageMatch[1] || '/';
    return Response.redirect(`${SITE_ORIGIN}${parent}`, 301);
  }

  // Old root-level blog URLs (/<slug>) → /blog/<slug> (301)
  const seg = pathname.replace(/^\/+|\/+$/g, '');
  if (seg && !seg.includes('/') && BLOG_SLUGS.has(seg)) {
    return Response.redirect(`${SITE_ORIGIN}/blog/${seg}`, 301);
  }

  return null;
}

export default {
  async fetch(request, env) {
    const url = new URL(request.url);

    // Root-level cache buster redirect to force fresh HTML load without caching
    if (url.pathname === '/' && !url.searchParams.has('__site_version')) {
      const version = Date.now();
      url.searchParams.set('__site_version', String(version));
      return new Response(null, {
        status: 302,
        headers: {
          'Location': url.toString(),
          'Cache-Control': 'no-store',
        },
      });
    }

    // Legacy WordPress URL cleanup (301 / 410 / 403) — mirrors public/.htaccess.
    // Runs before asset pass-through so e.g. /wp-content/*.jpg 410s instead of 404-ing.
    const legacyResponse = legacyWordPressResponse(url);
    if (legacyResponse) return legacyResponse;

    if (url.pathname === '/api/lead-webhook') {
      return forwardWebhook(request, env.WEBHOOK_URL || env.VITE_WEBHOOK_URL, {
        envName: 'WEBHOOK_URL',
        rejectedMessage: 'Webhook rejected the lead payload.',
        failedMessage: 'Webhook delivery failed.',
      });
    }

    if (url.pathname === '/api/workshop-webhook') {
      return forwardWebhook(request, env.WORKSHOP_WEBHOOK, {
        envName: 'WORKSHOP_WEBHOOK',
        rejectedMessage: 'Webhook rejected the workshop payload.',
        failedMessage: 'Workshop webhook delivery failed.',
      });
    }

    if (url.pathname.startsWith('/api/')) {
      return jsonResponse(404, { error: 'API route not found.' });
    }

    if (url.pathname.startsWith('/.well-known/')) {
      return wellKnownResponse(request, env);
    }

    if (url.pathname === '/version.json') {
      const versionResponse = await env.ASSETS.fetch(request);
      const headers = new Headers(versionResponse.headers);
      headers.set('Content-Type', 'application/json; charset=utf-8');
      headers.set('Cache-Control', 'no-store, no-cache, must-revalidate, max-age=0');
      headers.set('CDN-Cache-Control', 'no-store');
      headers.set('Pragma', 'no-cache');
      headers.set('Expires', '0');

      return new Response(versionResponse.body, {
        status: versionResponse.status,
        headers,
      });
    }

    // Static assets — pass through directly
    if (STATIC_EXT.test(url.pathname)) {
      return env.ASSETS.fetch(request);
    }

    // Page routes — fetch HTML and inject SEO tags
    const assetResponse = await env.ASSETS.fetch(request);
    const html = await assetResponse.text();
    const modifiedHtml = injectSeoTags(html, url.pathname);

    const headers = new Headers(assetResponse.headers);
    headers.set('Content-Type', 'text/html; charset=utf-8');
    // HTML must revalidate so phones do not keep an old document that points
    // at an older Vite bundle. Hashed assets remain cacheable below.
    headers.set('Cache-Control', 'no-store, no-cache, must-revalidate, max-age=0');
    headers.set('CDN-Cache-Control', 'no-store');
    headers.set('Pragma', 'no-cache');
    headers.set('Expires', '0');

    return new Response(modifiedHtml, {
      status: assetResponse.status,
      headers,
    });
  },
};
